config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :comments
  resources :articles

  get '/blog' => 'articles#index'

  root 'static_pages#homepage'

end

app/models/article.rb
class Article < ActiveRecord::Base
    has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    if params[:search]
      @articles = Article.where('title LIKE :search OR body LIKE :search', search: "%#{params[:search]}%")
    else
      @articles = Article.all
    end
  end


  def show
    @comment = Comment.new(article_id: @article.id)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :author, :body, :search)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to article_path(@comment.article), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :body, :article_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def show
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag articles_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Author</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= link_to article.title, article_path(article) %></td> 
        <td><%= article.author %></td>
        <td><%= article.body %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.body %>
</p>

<%= render 'comments/form' %>


<p.line> 
<p> 
<strong>Last comments:</strong> 
</p>
<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @article.comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <%= f.hidden_field :article_id, :value => @article.id %>

  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_footer.html.erb
    <div class="row">
        <div class="col-3">
            <%= image_tag("logo.png", class: 'logo-footer') %>
            <p>With a community of over 400+ million online users (and a majority age group being 18 to 29), wouldn’t you want to make sure that you are fully monitoring what people are posting on social networks?</p>
        </div>
        <div class="col-3">
            <h5>QUICK LINKS</h5>
        </div>
        <div class="col-3">
            <h5>SOCIAL</h5>
        </div>
        <div class="col-3">
            <h5>CONTACTS</h5>
        </div>
    </div> 

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-transparent bg-transparent">
  <%= image_tag("logo.png", class: 'logo-navbar') %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Blog</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          O nas
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Dmitry - UpWork</a>
          <a class="dropdown-item" href="#">Kasia - UpWork</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">GitHub </a>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>INVINITY</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= render "layouts/navbar" %>
</div> 
<%= yield %>

<div class="container">
  <%= render "layouts/footer" %>
</div>

</body>
</html>

app/views/static_pages/_icons.html.erb
<div class="container"> 
    <div class="title-icons-box">     
        <h3 class=title-icons>AREAS WE SERVE</h3>
    </div>
    <div class="text-community-box">
        <p class="text-community">With a community of over 400 million users (and a majority age group being 18 to 29), wouldn’t you want to make sure you’re monitoring what people are posting on social networks? Especially if the demographic of your audience falls in that age range.</p>
    </div>


    <div class="container container-icons-tel">
        <div class="row">
            <div class="col-4 col-visit">
                <div class="container box-text-icon">
                    <div class="row">
                        <div class="col-8"> 
                            <h4>VISIT</h4>
                            <p>Our values and ideals are our decision making guide.</p>
                        </div>
                        <div class="col-4">
                            <%= image_tag("visit-icon.png", class: 'visit-icon icon') %>
                        </div>
                    </div>
                </div>

                <div class="container box-text-icon">
                    <div class="row">
                        <div class="col-8"> 
                            <h4>SAVE</h4>
                            <p>We only release our products when we feel they meet our standards.</p>
                        </div>
                        <div class="col-4">
                            <%= image_tag("share-icon.png", class: 'share-icon icon') %>
                        </div>
                    </div>
                </div>

                <div class="container box-text-icon">
                    <div class="row">
                        <div class="col-8"> 
                            <h4>EXPLORE</h4>
                            <p>We rely on the same platform and tools our customers pay us for.</p>
                        </div>
                        <div class="col-4">
                            <%= image_tag("explore-icon.png", class: 'explore-icon icon') %>
                        </div>
                    </div>
                </div>

            </div> 
            <div class="col-4 col-phone">
                <%= image_tag("phone-zohar.png", class: 'phone-icon') %>
            </div>
            <div class="col-4 col-organize">
            <div class="container box-text-icon">
            <div class="row">
                <div class="col-8"> 
                    <h4>ORGANIZE</h4>
                    <p>Beautiful products to help people with creative ideas succeed.</p>
                </div>
                <div class="col-4">
                    <%= image_tag("organize-icon.png", class: 'organize-icon icon') %>
                </div>
            </div>
        </div>

        <div class="container box-text-icon">
            <div class="row">
                <div class="col-8"> 
                    <h4>COMMUNICATE</h4>
                    <p>Creative, stylish, and easy-to-manage online presence.</p>
                </div>
                <div class="col-4">
                    <%= image_tag("commuticate-icon.png", class: 'communicate-icon icon') %>
                </div>
            </div>
        </div>

        <div class="container box-text-icon">
            <div class="row">
                <div class="col-8"> 
                    <h4>SHARE</h4>
                    <p>Share stories and create an impactful online presence.</p>
                </div>
                <div class="col-4">
                    <%= image_tag("share-icon.png", class: 'share-icon icon') %>
                </div>
            </div>
        </div>

            </div>
        </div>
    </div>
</div>

app/views/static_pages/_slider.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
        <%= image_tag('watch1200.jpg', class: 'd-block w-100', alt: 'First slide')%>
        <div class="carousel-caption d-none d-md-block">
        <h5>title</h5>
        <p>1  2 3 4 5 6</p>
        </div>
    </div>
    <div class="carousel-item">
        <%= image_tag('portfolio.jpg', class: 'd-block w-100', alt: 'Second slide')%>
        <div class="carousel-caption d-none d-md-block">
        <h5>...</h5>
        <p>...</p>
        </div>
        </div>
    <div class="carousel-item">
        <%= image_tag('case-content-600x405.jpg', class: 'd-block w-100', alt: 'Third slide')%>
        <div class="carousel-caption d-none d-md-block">
        <h5>...</h5>
        <p>...</p>
        </div>
        </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/static_pages/homepage.html.erb
<div class="background">
    <div class="container main_page"
        <div class="container banner">
            <div class="line_main_page"> </div>
            <div class="container text-banner">
                <h3 class="company-name">Invinity</h3>
                <h3 class="subtitle">Apps Production</h3>
            </div>
        </div>
    </div>
</div>

<div class="background-homepage-grey">
    <div class="contact-page">
        <div class="white-line-contact"> </div> 
        <div class="container transparent-background-contact">
            <div class="row">
                <div class="col-md-4">
                    +48 666 458 458
                </div>
                <div class="col-md-4">
                    kasia.ekiert@gmail.com
                </div>
                <div class="col-md-4">
                    Europe
                </div>
            </div>
        </div> 
    </div>

    <div class="container">
        <div class="new_experience">
            <div class="row">
                <div class="col-md-4">
                    <h3>EXPERIENCE</h3>
                    <h6>We focus on the needs of small to middle market businesses, not the Fortune 5000.</h6>
                </div>
                <div class="col-md-4">
                    <h3>STRATEGY</h3>
                    <h6> We focus on the needs of small to middle market businesses, not the Fortune 5000.</h6> 
                </div>
                <div class="col-md-4">
                    <h3>SOCIAL</h3>
                    <h6> We focus on the needs of small to middle market businesses, not the Fortune 5000.</h6> 
                </div>
            </div>
        </div>
    </div>

    <div class="container"> 
        <div class="shaping-grey">
            <div class="row">
                <div class="col-md-4">
                    <p>SHAPING A NEW EXPERIENCE</p>
                </div>
                <div class="col-md-4">
                    <h5> We’re a creative branding and communications company of creative thinkers, strategists, digital innovators, designers and problem solvers. Our sense of curiosity brings</h5> 
                </div>
                <div class="col-md-4">
                    <h5> thinkers, strategists, digital innovators, designers and problem solvers (everyone gets a mention). Our sense of curiosity brings brands to life, gets them talking, and makes sure they’re heard above.</h5> 
                </div>
            </div>
        </div>
    </div>

    <div class="container"> 
        <div class="icons">
            <div class="row">
                <div class="col-md-4">
                    <%= image_tag("development.png", class: 'icon-mainpage')%>
                    <p class="icons-title">DEVELOPMENT</p>
                    <h5 class="icons-p"> We work alongside national and international organizations dedicated to sustainable development. </h5>
                </div>
                <div class="col-md-4">
                    <%= image_tag("Intergration.png", class: 'icon-mainpage') %>
                    <p class="icons-title">INTEGRATION</p>
                    <h5 class="icons-p"> We work alongside national and international organizations dedicated to sustainable development. </h5>
                </div>
                <div class="col-md-4">
                    <%= image_tag("responsibility.png", class: 'icon-mainpage') %>
                    <p class="icons-title">CREATIVITY</p>
                    <h5 class="icons-p"> We work alongside national and international organizations dedicated to sustainable development. </h5>
                </div>
            </div>
        </div>
    </div>

    <div class="container cont-slider">
        <%= render "slider" %>
    </div>
</div>

<div class="dark-background"> 
    <div class="container">
        <div class="slider-counter"
            <div class="row">
                <div class="col-md-4">
                    <div class="container">
                        <div class="row">
                            <div class="col-5">
                                <span class="timer" data-from="0" data-to="12" data-speed="5000" data-refresh-interval="50"></span>
                                <p>YEARS OF EXPERIENCE</p>
                            </div> 
                            <div class="col-7 text-slider-counter">
                                <h4>Years of hard work, commitments for better productivity, work in different time zones.</h4>
                            </div>
                        </div> 
                    </div>
                </div> 
                <div class="col-md-4">
                    <div class="container">
                        <div class="row">
                            <div class="col-5">
                                <span class="timer" data-from="0" data-to="5" data-speed="5000" data-refresh-interval="50"></span>
                                <p>CUPS OF COFFEE/PER DAY</p>
                            </div> 
                            <div class="col-7 text-slider-counter">
                                <h4>Because we love it! Because we need it!</h4>
                            </div>
                        </div> 
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="container">
                        <div class="row">
                            <div class="col-5">
                                <span class="timer" data-from="0" data-to="100" data-speed="5000" data-refresh-interval="50"></span>
                                <p>5-STAR REVIEWS</p>
                                </div> 
                            <div class="col-7 text-slider-counter">
                                <h4>Where you will find the same quality of service and dedication around the world</h4>
                            </div>
                        </div> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 

<div class="grey-icons-background">
    <%= render "icons" %>
</div> 

<div class="recomendation-background">
    <div class="container">
        <div class="row">
            <div class="col-6">
                <div class="recommend">
                    <div class="line_people_say"> </div>
                    <div class="people say">
                        <h3 class="people-say-text">WHAT PEOPLE SAY</h3>
                    </div>
                </div>
                <div class="recomment_text">
                    <div class="row">
                        <div class="col-3">
                        </div> 
                        <div class="col-9">
                            <h3 class="go_without_text">It should go without saying that designers, now more than ever, have to design with a mobile-first mentality.</h3>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-2">
                        <div class="photo-client">
                            <%= image_tag("klient.jpg", class: 'klient-jpg') %>
                        </div>
                    </div>
                    <div class="col-10">
                        <p>by John Doe, Company CEO</p>
                    </div>
                </div>


            </div> 
            <div class="col-6">
                <%= image_tag("Amanda.png", class: 'face-recomentation') %>
            </div> 
        </div>
    </div>
</div>

<div class="background-dark-staff">
   
</div>

<div class="background-fair-cooperation">

</div>


</div>